### ISSUE TITLE
Problems with using

### ISSUE THREAD

**Issue by Tuburni** [olgierd/ad8317_powermeter#2]
Hello

I have a problem's
If I boot the Arduino in calibration mode (by shorting one of the buttons), and change the value of band_labels to 1G2 and press SAVE, then unplug the arduino from the power and turn it on in normal mode, for some reason the default value of 144 is displayed, and not in 1G2 which I chose
What is the problem?

**Comment by olgierd** [comment]
Sorry, I'm unable to replicate it.
