### ISSUE TITLE
Please share your calibrations

### ISSUE THREAD

**Issue by whoim2** [olgierd/ad8317_powermeter#3]
My TiniSA can produce signals from -40 to -18.8. I calibrated the lower value but I have nothing to calibrate the upper one with. If someone shares the calibrations (letter p in the serial monitor) - thank you, I’ll compare I'll add the lower values ​​to the eeprom.

**Comment by olgierd** [comment]
I can share mine in few days, calibrated using a decent signal generator. You can ping me if I don't in a week or so ;-)

**Comment by whoim2** [comment]
> I can share mine in few days, calibrated using a decent signal generator. You can ping me if I don't in a week or so ;-)

Thank you, I'll wait) Alternatively, I can replace 
#define CAL_UP -10 to #define CAL_UP -18.8 How does my generator allow this?

**Comment by whoim2** [comment]
im set #define CAL_UP -18.8 and calibrate from tinySA, its worked but between the values top and bottom the measurements are incorrect

**Comment by olgierd** [comment]
Hi,

here's my calibration, should be pretty good up to 2.3 GHz - that's my generator's limit: 

Calibration...
Lower point: -40
Upper point: -10
10M L: 631 H: 298
20M L: 629 H: 296
50M L: 630 H: 298
144 L: 628 H: 293
430 L: 625 H: 289
1G2 L: 610 H: 276
2G4 L: 580 H: 248
5G L: 563 H: 232
10G L: 563 H: 232
